server:
  port: 8563
spring:
  application:
    name: seconds_kill
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/seconds_kill?rewriteBatchedStatements=true&serverTimezone=GMT%2b8
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      max-lifetime: 1800000
      max-pool-size: 15
      min-idle: 200
      connection-test-query: select 1
  rabbitmq:
    virtual-host: /
    host: 47.105.40.52
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 10 #最大重试次数
          max-interval: 10000 #重试最大时间间隔(ms)
          initial-interval: #c重试间隔时间(ms)
          multiplier: 5 #应用于前一重试间隔的乘法器。

  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 1024
        max-wait: -1ms
        max-idle: 200
    database: 2

